### ISSUE TITLE
Make wallet connection a last step

### ISSUE THREAD

**Issue by payvint** [skalenetwork/portal#110]
## Idea 
Ask to connect to the wallet at the last step

## Problem
If user joins from browser(without wallet) or mobile without wallet - user can not see tiles and functionality of the bridge and simply leave the page

## Solution
Instead showing the first screen as wallet connection page
we can move this page to the end - when the user actually want to interact with a bridge (Transfer, recharge, get sfuel, etc)
And allow users without wallet to navigate through the bridge ui

If wallet is not connected:
Balances: "Wallet is not connected" or make "0 TOKEN" dark
Sfuel Popup: Do not show
Recharge Popup: Do not show

**Comment by PolinaKiporenko** [comment]
done
