### ISSUE TITLE
Migrate Network UI functionality into SKALE Bridge/SKALE Portal

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/portal#113]
[Network UI](https://github.com/skalenetwork/network-ui) currently exists as a separate React application that provides information on chain endpoints and block explorer links.

To enhance user experience and create a central place, the goal is to migrate these features into SKALE Bridge/SKALE Portal. This consolidation will make it easier for users to access various functionalities from a single point, thereby improving the overall UX.

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: 2.0.0-develop.0 

All the functionality of Network UI is present in new version of Portal, except ABIs, generation type, multitransaction info and date of creation. 
It's better to add it back in the next release. 

![Image](https://github.com/skalenetwork/portal/assets/105824131/6d63c3ab-472f-439f-81eb-b6948aa859a6)



![Image](https://github.com/skalenetwork/portal/assets/105824131/0aec2f25-60b5-49ef-ae64-8a6dff53a3e0)
