### ISSUE TITLE
Show ToS modal only on Bridge-related pages

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/portal#115]
SKALE Bridge Terms of Service modal should be shown only on Bridge-related pages:

- Transfer
- History
- Portfolio

ToS shouldn't be displayed for 

- Chains page 
- Apps page 
- all other pages

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: 2.0.0-develop.7

ToS are shown only on Transfer, History, Portfolio pages.
