### ISSUE TITLE
History page crashes with not connected wallet

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/portal#119]
**To Reproduce**
1. Go to https://bridge-ui-git-qa-skale-network.vercel.app/
2. Scroll ToS
3. Click on "Agree to terms"
4. Don't connect a wallet
5. Click on "History"
6. See error in dev console logs

**Screenshots**
<img width="1437" alt="Знімок екрана 2023-10-25 о 15 25 34" src="https://github.com/skalenetwork/bridge-ui/assets/105824131/97a20f04-c474-4bd3-8b16-a5ffba024cc1">

**Desktop (please complete the following information):**
- OS: macOS 14.0
- Browser: chrome 118.0.5993.88
- Portal version: 2.0.0 - develop

**Comment by yatsunastya** [comment]
it doesn't work with connected wallet and completed transaction as well.

https://github.com/skalenetwork/bridge-ui/assets/105824131/7f0dc757-08eb-47a5-bf17-623346e13b50

**Comment by PolinaKiporenko** [comment]
needs to be retested
