### ISSUE TITLE
Small fixes list 

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/portal#120]
- [x] update FAQ
- [ ] update support popup window style
- [x] stats don't work
- [ ] change padding color to black
- [x] completed transactions and history
- [x] the link sends to the old version of bridge ⬇️

![image](https://github.com/skalenetwork/bridge-ui/assets/105824131/ebdc15ba-be31-4c96-973b-87b0015efdc6)

- [x] change balance length for destination chain ⬇️
<img width="578" alt="Знімок екрана 2023-10-25 о 18 13 55" src="https://github.com/skalenetwork/bridge-ui/assets/105824131/95a5987e-ae84-4d89-800a-d651c8079ef3">

**Comment by dmytrotkk** [comment]
Fixed all, except 

- change padding color to black
- update support popup window style - should be fixed in Zendesk
