### ISSUE TITLE
Show chain specific statistics in Portal

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/portal#122]
We need to visualize schain-specific stats in Portal. Data can be retrieved from stats API:
https://stats.explorer.mainnet.skalenodes.com/v2/stats/[SCHAIN_NAME]

Fabio to add context

**Comment by TMSCHT** [comment]
Ideally, we can choose between specific chain and overall stats and go back in history more than just 6 months (default view can remain the same).

**Comment by dmytrotkk** [comment]
Already implemented in Portal v3:

<img width="888" alt="Screenshot 2024-08-29 at 17 13 09" src="https://github.com/user-attachments/assets/14dd7697-df39-45ad-ada0-24153c8a0c89">

Data that we're pulling from Stats API for each chain:

- Total transactions
- Gas saved
- Unique active wallets
- Total blocks

Data pulled directly from block explorers:

- Daily transactions

cc @DmytroNazarenko  @TMSCHT @PolinaKiporenko
