### ISSUE TITLE
Transfers number is wrong in history

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/portal#125]
**Describe the bug**
The number of transfers is wrong on transaction history page, in case of checking it during the transfer. 

**To Reproduce**
1. Create transfer from Mainnet to Calypso Hub
2. Go to the last step/transaction (transfer Europa Hun to Calypso Hub) but don't complete it
3. Go to "History" page
4. Look at the number of transfers

**Screenshots**
![image](https://github.com/skalenetwork/portal/assets/105824131/8ef058bc-f5b1-4ee8-a16a-ff0f63dda609)

**Desktop (please complete the following information):**
- OS: macOS 14.0
- Browser: chrome 118.0.5993.88
- Portal version: 2.0.0 - develop

**Comment by dmytrotkk** [comment]
Fixed. 

Now shows the number of completed transfers in history + current transfer if present.
