### ISSUE TITLE
Add dedicated apps and games page

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/portal#185]
We can enhance the user experience of the SKALE Portal by introducing new page called 'Apps and Games' page. 
These additions are aimed at improving discoverability of features and applications within the SKALE ecosystem.

Objective: Create a new page titled 'Apps & Games' which will serve as a discovery platform for users to find and interact with a curated list of applications hosted on the SKALE network. Should be available under /apps url.

Reference: Apps/Marketplace page in the latest Blockscout UI.

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: [2.3.0-develop.5](https://github.com/skalenetwork/portal/releases/tag/2.3.0-develop.5)

- Apps for each chain are displayed on "Chains" page now
<img width="1437" alt="Знімок екрана 2024-07-29 о 12 48 30" src="https://github.com/user-attachments/assets/91682df1-c019-41ad-8046-a6bde35e5a7c">

- Also all the apps are displayed on hub page in "Apps" tab
<img width="1440" alt="Знімок екрана 2024-07-29 о 12 55 05" src="https://github.com/user-attachments/assets/6e367744-0bb4-4a02-b493-24237737c254">
