### ISSUE TITLE
Request Europa ETH on Nebula Mainnet added to Portal

### ISSUE THREAD

**Issue by TheGreatAxios** [skalenetwork/portal#197]
Can you please add **0xaB01BAd2C86e24D371A13eD6367bdCa819589C5D** Europa ETH to Portal?

**Comment by dmytrotkk** [comment]
already added
https://github.com/skalenetwork/portal/blob/5594058da05b9a7f08a37bcaa6945e93cc6f7073/config/mainnet.ts#L491
