### ISSUE TITLE
Add TRBP Token to Testnet Portal

### ISSUE THREAD

**Issue by TheGreatAxios** [skalenetwork/portal#204]
Please map Tellor Playground token from Holesky to Europa testnet. 

TRBP on Holesky: 0x34fae97547e990ef0e05e05286c51e4645bf1a85
TRBP on Europa: 0x92732c3e59af2ea6aa2e886da5959fe952ce2d24
wTRBP on Europa: 0x65f2acbe95cb70d702a6eef307f6f88c636d7cb4

**Comment by TheGreatAxios** [comment]
Map to Nebula Testnet as well: 0x703b996c6634194778666b7eadb177cb49b2d277

TRBP on Nebula Testnet: 0x703b996c6634194778666b7eadb177cb49b2d277

**Comment by dmytrotkk** [comment]
TRBP is live on Testnet
