### ISSUE TITLE
Empty page after account change

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/portal#211]
**Describe the bug**
In case of changing account with escrow to regular one at the "Stake SKL" page, page reloads and becomes empty. 
  
**Version:**
2.2.0-develop.0

**To Reproduce**
1. Connect to the portal with escrow account
2. Choose escrow delegation and validator 
3. Go to "Stake SKL" page
4. Change connected account (with escrow) to regular account
5. See empty page

**Expected behavior**
The case must be handled and informative message is displayed. 

**Screenshots**

https://github.com/skalenetwork/portal/assets/105824131/40c851b3-36d4-42a1-a960-8a26bbe679c3

**Comment by yatsunastya** [comment]
After changing with escrow to regular one at the "Stake SKL" page, error message is displayed and it's impossible to close it.

https://github.com/skalenetwork/portal/assets/105824131/fe45b6fc-9168-42ae-9dc8-f327ad3d0403

**Comment by dmytrotkk** [comment]
Fixed in 2.3
<img width="906" alt="Screenshot 2024-07-09 at 18 10 51" src="https://github.com/skalenetwork/portal/assets/15244591/96a375d3-78ea-4190-87f2-12e9759b88f2">

**Comment by yatsunastya** [comment]
Still relevant. 
Version: [2.3.0-develop.0](https://github.com/skalenetwork/portal/releases/tag/2.3.0-develop.0)

<img width="914" alt="Знімок екрана 2024-07-16 о 17 53 29" src="https://github.com/user-attachments/assets/c5f1b178-67f3-4850-9a6d-13b0e50a1989">

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: [2.3.0-develop.2](https://github.com/skalenetwork/portal/releases/tag/2.3.0-develop.2)
<img width="869" alt="Знімок екрана 2024-07-17 о 17 22 30" src="https://github.com/user-attachments/assets/3938c2f8-e3d6-43f2-ba29-dc3a80b76321">
