### ISSUE TITLE
Exit Gas Wallet balance is not displayed

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/portal#220]
**Describe the bug**
Exit Gas Wallet balance isn't displayed and it's not possible to recharge it. In case of modifying recharge amount, it shows "Insufficient ETH balance", but balance is OK.

**Version:**
2.2.0-develop.0

**To Reproduce**
1. Connect to Portal 
2. Choose S2M transfer
3. Click on Exit Gas Wallet OK
4. See that there is no balance info

**Screenshots**

<img width="1102" alt="Знімок екрана 2024-04-09 о 13 48 04" src="https://github.com/skalenetwork/portal/assets/105824131/c51587d3-b8ef-4729-b357-e81696ad501b">

**Comment by dmytrotkk** [comment]
Issue with contracts setup on QA network - owner should execute `CommunityPool.setMultiplier(3, 2)` on mainnet IMA contracts to fix.
