### ISSUE TITLE
Error details message is displayed in one line

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/portal#221]
**Version:** 
2.2.0-develop.0

**Expected behavior**
If an error message is too long, it's split to several lines.

**Screenshots**

<img width="1429" alt="Знімок екрана 2024-04-09 о 17 33 19" src="https://github.com/skalenetwork/portal/assets/105824131/2c0a1a2d-45d7-4754-8367-587e42f8b010">

**Comment by PolinaKiporenko** [comment]
moved to the next release

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: [3.2.0-beta.0](https://github.com/skalenetwork/portal/releases/tag/3.2.0-beta.0)

Full error message is displayed on the screen.
![Image](https://github.com/user-attachments/assets/d902d508-b73c-47ae-b30f-73fa509d592d)
