### ISSUE TITLE
Page isn't updated after account changing 

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/portal#225]
**Describe the bug**
After changing account, page info isn't updated and it's still possible to click "Transfer" button (even if there are no tokens on the balance) and confirm "Approve" transaction.

**Screenshots**

https://github.com/skalenetwork/portal/assets/105824131/9795b7c7-0a01-46de-8967-7de57229254b

**Comment by PolinaKiporenko** [comment]
moved to the next release

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: [3.2.0-beta.0](https://github.com/skalenetwork/portal/releases/tag/3.2.0-beta.0)

The issue is fixed

https://github.com/user-attachments/assets/e906c779-6744-448c-88a7-4479fc8d3f02
