### ISSUE TITLE
Merge portal, metaport and ima-js

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/portal#245]
This ticket proposes merging the portal, metaport, and ima-js repositories for a simplified development workflow.

- The portal repository will become the base, with a dedicated packages folder to house each project's code.
- We will have separate build configurations and GitHub Actions jobs for each package.

This approach improves maintainability and simplifies the CI/CD pipeline.

We can start with portal + metaport integration first and add ima-js later

**Comment by oleksandrSydorenkoJ** [comment]
Verified on Legacy network 
Portal version: [4.0.0-beta.6](https://github.com/skalenetwork/portal/releases/tag/4.0.0-beta.6)
