### ISSUE TITLE
Create python agent collect dApps data and gas price

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/portal#251]
**Is your feature request related to a problem? Please describe.**

- We need to collect and cache data from block explorers with dApp stats
- We need data about historic gas price from Ethereum Mainnet
- We need stats from SKALE Chains (active wallets, transaction, etc)

**Describe the solution you'd like**

The proposition is to create a small python-based agent that will pull data from block explorers and save them to JSON file. 
Then, container with this agent can be hosted on the same machine where SKALE Proxy is running. 

This way we can utilise nginx, certs and env variables that we already in place.

**Additional context**

It's also possible to use Stats API to get better stats for chains.

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: [2.3.0-develop.4](https://github.com/skalenetwork/portal/releases/tag/2.3.0-develop.4)

All the metrics displayed on the Portal correspond to those on the block explorer:
- daily transactions
- total transactions
- total addresses
- *total blocks may differ as they are updated with some time difference. 
- total transactions (on the app page) 

![Image](https://github.com/user-attachments/assets/029f3a4a-be3f-4b7d-88f0-1fa10a4d568e)



![Image](https://github.com/user-attachments/assets/00c79cf7-a394-45f5-aa17-af73a62f2ebb)
