### ISSUE TITLE
Add page for validators to interact with pending delegations 

### ISSUE THREAD

**Issue by PolinaKiporenko** [skalenetwork/portal#284]
We used to have a page for accepting pending delegations for the validators. However, this site is not being maintained and is deprecated. Therefore, we need to add such functionality to the Portal.

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: [3.2.0-beta.0](https://github.com/skalenetwork/portal/releases/tag/3.2.0-beta.0)

:heavy_check_mark: In case of PROPOSED delegations, notifications are displayed
![Image](https://github.com/user-attachments/assets/62573834-31b3-4420-8e36-6a81020324ca)

Delegations statuses:
:heavy_check_mark: PROPOSED
:heavy_check_mark: ACCEPTED
:heavy_check_mark: DELEGATED
:heavy_check_mark: COMPLETED
:heavy_check_mark: CANCELED
:heavy_check_mark: REJECTED
:heavy_check_mark: UNDELEGATION_REQUESTED
