### ISSUE TITLE
Implement Ecosystem page

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/portal#312]
For Portal 2.3 new Ecosystem page should be implemented.

Requirements:

- Ecosystem page should be available from the Drawer menu
- Ecosystem page should include all apps and games from all Hub chains
- Tabs on the Ecosystem page: All (default), New, Favourites, Trending
- Search bar and categories selector

App cards should include:

- App logo
- App name and short description
- Tags
- Hub chain(s)
- URLS: website, twitter, tg, discord (optional)
- Like button

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: [3.0.0-develop.1](https://github.com/skalenetwork/portal/releases/tag/3.0.0-develop.1)

**App cards:**
:heavy_check_mark: App logo
:heavy_check_mark:  App name and short description
:heavy_check_mark:  Tags
:heavy_check_mark:  Hub chain
:heavy_check_mark:  URLS: website, twitter, telegram, discord 
:heavy_check_mark:  Like button

![Image](https://github.com/user-attachments/assets/d976f24a-468a-4ed5-a86d-93989a6c6b44)

**Ecosystem page:**
:heavy_check_mark: Ecosystem page is available from the Drawer menu
:heavy_check_mark: Ecosystem page includes all apps and games from all Hub chains
:heavy_check_mark: Tabs on the Ecosystem page: All (default), New, Favourites, Trending
:heavy_check_mark: Search bar and categories selector

https://github.com/user-attachments/assets/105ab440-b674-4a7d-944c-6a685c664c3d
