### ISSUE TITLE
Search functionality for apps, add multi-tier categories, add filtering

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/portal#313]
Apps and games on Ecosystem page should be searchable by:

- App name
- Hub chain name (e.g. filter by 'Europa' to show only apps from this hub)
- Tags

Sub-categories for tags should be implemented. 
All data should be sourced from skale-network repo metadata.

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: [3.0.0-develop.1](https://github.com/skalenetwork/portal/releases/tag/3.0.0-develop.1)

- All the apps are searchable by app name and hub chain name.

![Image](https://github.com/user-attachments/assets/69886dc9-9275-4b55-a2e1-4e64b9821700)

- All the apps can be filtered by category filter.

![Image](https://github.com/user-attachments/assets/945c5873-af53-4685-ba03-6713dc72013a)

- All the apps can be filtered by hub chain name and category filter (together).

![Image](https://github.com/user-attachments/assets/2f2c7422-54c9-40e0-80f8-b912a3f48c89)
