### ISSUE TITLE
Add Favorites and trending dApps

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/portal#315]
- Logged-in users should be able to add apps to Favorites
<img width="409" alt="Screenshot 2024-08-02 at 12 56 41" src="https://github.com/user-attachments/assets/a449afbd-90d7-4371-8b50-1bff3f9df1ad">  

- Users should be able to view all apps that they've added to Favorites on the Favorites tabs on Ecosystem page

<img width="692" alt="Screenshot 2024-08-02 at 12 58 12" src="https://github.com/user-attachments/assets/2f3df3b5-2e85-49e2-ae04-7aa0b9039795">

- Trending apps should be sorted by the number of total favs on the app
- Top 15 apps should be displayed on the Trending

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: [3.0.0-develop.3](https://github.com/skalenetwork/portal/releases/tag/3.0.0-develop.3)

:heavy_check_mark:  Signed-in user is able to add apps to "Favorites" and see them in "Your Favorites"
:heavy_check_mark:  Signed-in user see favorite apps in "Your Favorites"
:heavy_check_mark:  All the favorite apps are saved for signed-in users
:heavy_check_mark:  Top 12 apps with the biggest number of likes are displayed in Trending category
:heavy_check_mark:  Trending apps are sorted by number of likes
