### ISSUE TITLE
New Home page

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/portal#316]
Updated Home page should feature the following sections:

- Explore Portal (cards with links to the main functionality)
- New dApps on SKALE (15 latest apps, horizontal scrolling)
- Trending dApps on SKALE (top 15 app sorted by favs number)
- Top Categories (Categories with the most games in it)

Design mockup can be found in the Figma file.

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: [3.0.0-develop.1](https://github.com/skalenetwork/portal/releases/tag/3.0.0-develop.1)

**Home page includes:**
:heavy_check_mark: Explore Portal (with 4 cards: Bridge, Stake, SKALE Chains, Ecosystem)
:heavy_check_mark: Your Favorites (with apps that were liked by signed in user)
:heavy_check_mark: New dApps on SKALE (with the latest 12 apps)
:heavy_check_mark: Trending dApps on SKALE (with top 12 apps)
:heavy_check_mark: Top Categories (with categories with the biggest number of apps)



https://github.com/user-attachments/assets/def630e1-0e55-4fe5-a1d2-3b40f1feccc0
