### ISSUE TITLE
Implement Sign-in with Ethereum functionality, update RainbowKit to v2

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/portal#319]
Users should be able to sign-in using Ethereum.
RainbowKit have to be updated to v2 to support this feature.

More details to be added.

https://docs.login.xyz/
https://www.rainbowkit.com/docs/authentication#set-up-sign-in-with-ethereum-and-nextauthjs

**Comment by dmytrotkk** [comment]
@yatsunastya @PolinaKiporenko 

Features that needs to be re-tested:

- S2S transfers
- Routed transfers (M -> S -> S, S -> S -> M)
- Staking (check at least one tx)
- sChain payments (check  at least one tx)


New wallets that should be tested:

- coinbaseWallet
- rainbowWallet
- rabbyWallet

(test with S2S and M2S transfers)

**Comment by yatsunastya** [comment]
Version: 2.3.0-develop.8/ 2.3.0-develop.9

Staking and sChain payments transactions pass successfully.

Metamask - :white_check_mark:  (all types of transfers)
Rabby Wallet - :white_check_mark:  (all types of transfers)
Enkrypt - :white_check_mark: ('switch network' doesn't work on testnet, but it works on Mainnet)
Coinbase - :white_check_mark: (all types of transfers)
Rainbow Wallet - :x: 
```
TransactionRejectedRpcError: Transaction creation failed.

Details: User rejected the request.
Version: 2.19.4
    at YU.delay.count (index-291fb394.js:857:40732)
    at async N (index-291fb394.js:857:40139)
    ```

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: [3.0.0-develop.6](https://github.com/skalenetwork/portal/releases/tag/3.0.0-develop.6)

Rainbow Wallet:
:x:  transfers from Mainnet to schain fail (BUT it works on Mainnet environment)
:heavy_check_mark: transfers between chains work (BUT sometimes there is an [issue](https://github.com/skalenetwork/portal/issues/356) with switching networks)
:heavy_check_mark: transfers from schain to Mainnet work (BUT sometimes there is an [issue](https://github.com/skalenetwork/portal/issues/356) with switching networks)
