### ISSUE TITLE
Add Screenshots section to the app details page

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/portal#322]
App details page should feature a carousel with app screenshots, see mockup below:

<img width="758" alt="Screenshot 2024-08-08 at 16 13 37" src="https://github.com/user-attachments/assets/7d7a7c16-e031-4764-97aa-81e58cf73695">

We will need to collect all screenshots & store them in `skale-network` repo or on S3 bucket.

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: [3.1.0-beta.0](https://github.com/skalenetwork/portal/releases/tag/3.1.0-beta.0)

After adding screenshots to the corresponding directory in skale-network repository, they are displayed on dApp page on Portal. 
![Image](https://github.com/user-attachments/assets/091eff98-a321-4631-ad8a-da8494b16514)
