### ISSUE TITLE
Update metrics collector to store historic app stats

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/portal#326]
Metric collector has to be updated to store historic data about apps:

- DB should be added
- Probably should be merged into stats-api repo
- In the first version we need to store data about transactions from the app for:

1. last day
2. last 7 days
3. last 30 days
4. total txs

More details will be added later.

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: [3.1.0-beta.2](https://github.com/skalenetwork/portal/releases/tag/3.1.0-beta.2)

Transaction are displayed for:
- 1 day
- 7 days
- 30 days
- total
![Image](https://github.com/user-attachments/assets/eb2d85cb-131a-4f5d-8675-5f20846f4256)

BUT 
There is an [issue](https://github.com/skalenetwork/portal/issues/407) with delay
