### ISSUE TITLE
Category icons are displayed out of app frame

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/portal#333]
**Describe the bug**
If an application has 7 or more categories, after expanding them, category icons and app description are displayed out of app frame

It's better to make button "Add to favorites" static, so it's not moved after expanding all the category icons. 
And make "Hide" button with symbol instead of word. 

**To Reproduce**
1. Go to "Ecosystem" page
2. Choose app with +5 categories
3. Expand them 

**Screenshots**
<img width="1033" alt="Знімок екрана 2024-08-19 о 19 44 16" src="https://github.com/user-attachments/assets/2e3dd228-3293-41e4-a8dd-450da168ce28">

**Comment by dmytrotkk** [comment]
fixed on desktop and mobile

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: [3.0.0-develop.6](https://github.com/skalenetwork/portal/releases/tag/3.0.0-develop.6)

:heavy_check_mark:  "Add to favorites" button doesn't move
:heavy_check_mark: Category icons are displayed in several rows (not one line)

![Image](https://github.com/user-attachments/assets/71006fa9-2ec4-4cc7-be2b-e63075795010)
