### ISSUE TITLE
Category icons are displayed in one line

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/portal#338]
**Describe the bug**
After selecting 7+ categories in drop-down menu, all of the extra category icons, number of projects and "Clear all" button are displayed in one line. 

**To Reproduce**
1. Go to 'Ecosystem' page 
2. Click on 'Browse by category' button
3. Choose 7+ categories
4. See all the icons in one line

**Version:** [3.0.0-develop.1](https://github.com/skalenetwork/portal/releases/tag/3.0.0-develop.1)

**Screenshots**
<img width="1132" alt="Знімок екрана 2024-08-20 о 16 20 24" src="https://github.com/user-attachments/assets/10bda8ec-d6f8-45ec-a7e0-8deadba91157">

**Comment by dmytrotkk** [comment]
fixed on desktop & mobile
<img width="1331" alt="Screenshot 2024-08-27 at 13 58 12" src="https://github.com/user-attachments/assets/5d4c631f-b70e-4f80-9b5f-232910680e3f">
<img width="1331" alt="Screenshot 2024-08-27 at 13 58 24" src="https://github.com/user-attachments/assets/5ab05606-5dc1-44f3-a149-cb9d5377b7ae">
