### ISSUE TITLE
Fix projects number in category filter

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/portal#339]
**To Reproduce**
1. Go to 'Ecosystem' page
2. Choose 'New' tag
3. Choose category that has trending apps
4. Pay attention to projects` number and number of projects that are displayed

**Version:** [3.0.0-develop.1](https://github.com/skalenetwork/portal/releases/tag/3.0.0-develop.1)

**Screenshots**
<img width="914" alt="Знімок екрана 2024-08-20 о 17 04 28" src="https://github.com/user-attachments/assets/64e7b7eb-413c-402c-8965-95456822f513">

**Comment by dmytrotkk** [comment]
fixed

https://github.com/user-attachments/assets/c1fafdbb-f764-47a0-8192-e58076080957

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: [3.0.0-develop.6](https://github.com/skalenetwork/portal/releases/tag/3.0.0-develop.6)

:heavy_check_mark:  Projects number is fixed in all of the categories.
