### ISSUE TITLE
Category filter doesn't work in "Favorites" and "Trending"

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/portal#340]
**Describe the bug**
It is possible to choose any category in categories filter while exploring "Trending" apps or "Favorites", but the filter doesn't work. 

**Version:** [3.0.0-develop.1](https://github.com/skalenetwork/portal/releases/tag/3.0.0-develop.1)

**Screenshots**
<img width="886" alt="Знімок екрана 2024-08-20 о 18 08 07" src="https://github.com/user-attachments/assets/7b19c3b9-14c5-4585-b7ec-1e0f2f69e3ba">

**Comment by dmytrotkk** [comment]
fixed

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: [3.0.0-develop.6](https://github.com/skalenetwork/portal/releases/tag/3.0.0-develop.6)


https://github.com/user-attachments/assets/a49495d4-497c-465f-ba26-490719653cec
