### ISSUE TITLE
There is no "Sign in" pop up window

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/portal#341]
**Version:** [3.0.0-develop.1](https://github.com/skalenetwork/portal/releases/tag/3.0.0-develop.1)

**To Reproduce**
1. Connect wallet but don't sign in
2. Go to 'Ecosystem' page
3. Click on 'Add to favorites'
4. There is no "Sign in" pop up window and nothing happens

**Expected behavior**
There is "Sign in" pop up window

**Screenshots**
<img width="1205" alt="Знімок екрана 2024-08-20 о 18 39 05" src="https://github.com/user-attachments/assets/dd28057b-f4af-450d-939c-cf89ecc02f08">

**Comment by yatsunastya** [comment]
There is no "Connect wallet" pop up window at app page.

![Image](https://github.com/user-attachments/assets/a765cbb4-099e-47fd-9b48-5ef5b820cb46)

**Comment by dmytrotkk** [comment]
fixed

https://github.com/user-attachments/assets/80822dd5-1541-4ccd-bba8-d52939b6a9cb

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: [3.0.0-develop.6](https://github.com/skalenetwork/portal/releases/tag/3.0.0-develop.6)

:heavy_check_mark:  There is "Sign-in" pop-up window after clicking on "Add to favorites" on Ecosystem page.
:heavy_check_mark:  There is "Connect wallet" and "Sign-in" pop-up windows after clicking on "Add to favorites" on app page.
