### ISSUE TITLE
Issue Running on Testnet Branch

### ISSUE THREAD

**Issue by TheGreatAxios** [skalenetwork/portal#346]
**Goal**
To add tokens to the testnet config. 

**Describe the bug**
Invalid parameters were provided to the RPC method. Double check you have provided the correct parameters. Details: Expected null or array with at least one valid string HTTPS URL 'blockExplorerUrl'. Received: undefined Version: viem@1.21.3

**To Reproduce**
1. Clone the GitHub repo with `-b testnet` flag
2. Run `NETWORK_NAME=testnet bash build.sh && export VITE_MAINNET_ENDPOINT=https://holesky.drpc.org && bun dev`
3. Attempt to bridge from Holesky -> Juicy-Low-Small-Testnet

**Expected behavior**
This should initiate the transfer via Metamask

**Screenshots**
![image](https://github.com/user-attachments/assets/857b468f-5388-407c-931d-5012dc4b1c7a)

**Comment by dmytrotkk** [comment]
@TheGreatAxios 

should be fixed now, in the latest version for testnet setup we have a shortcut:

```bash
bun build:testnet
```
