### ISSUE TITLE
Move History menu item to the Bridge page

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/portal#363]
History menu item should be moved to the Bridge page:

<img width="260" alt="Screenshot 2024-08-29 at 17 10 13" src="https://github.com/user-attachments/assets/64807aaf-6633-44ce-b9c2-c1a5daadc8f1">

Also, menu section should be called "Transfer" and metaport page should be called "Bridge"

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: [3.1.0-beta.0](https://github.com/skalenetwork/portal/releases/tag/3.1.0-beta.0)

:heavy_check_mark:  Menu section is renamed to "Transfer"
![Image](https://github.com/user-attachments/assets/42d74938-d000-4d4e-bebb-c93c058f2a05)

:heavy_check_mark: "History" is moved to Bridge page
![Image](https://github.com/user-attachments/assets/9e325f31-b87f-49f8-8526-ea1fb6edc411)
