### ISSUE TITLE
Add tooltips with general info to all pages

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/portal#365]
All major pages on the Portal should have info icon on the right side from the H1 headline with tooltip that will contain explanation for the page.
- Bridging I - info
- Add "i" that w. hover explains staking
- Add "i" that w. hover explains hubs

<img width="1325" alt="Screenshot 2024-08-29 at 17 28 53" src="https://github.com/user-attachments/assets/48f187f2-8698-446b-a679-19784e0eb275">

**Comment by PolinaKiporenko** [comment]
### Bridging
Transfer your assets to the SKALE Network and move easily across SKALE Chains to access a variety of dApps.

### Staking
Delegate your SKL tokens to help secure the SKALE Network and earn rewards.

### SKALE Chains
SKALE Chains are custom blockchains within the SKALE Network designed to power specific dAps and use cases.

### On-Ramp
Use your preferred fiat currency to get USDC directly on the SKALE Europa Hub.

### Ecosystem
Discover and explore all the dApps available across the SKALE Network in one place.

### Stats
Check live SKALE Network statistics like active wallets, transactions, and total gas fees saved by users.

### Validators
Explore validators that secure the SKALE Network and choose your preferred ones to stake SKL tokens with to earn rewards.

**Comment by yatsunastya** [comment]
Checked ✅
Version: [3.1.0-beta.0](https://github.com/skalenetwork/portal/releases/tag/3.1.0-beta.0)

### Bridging
![Image](https://github.com/user-attachments/assets/abdaef4d-4faa-4890-b14c-61e8319c73f5)
### Validators
![Image](https://github.com/user-attachments/assets/9b8373df-0c58-4040-88f6-4b0483262ed8)
### Stats
![Image](https://github.com/user-attachments/assets/b3cd47a8-99e9-4750-8bb5-fe6bac6ad77e)
### Ecosystem
![Image](https://github.com/user-attachments/assets/70f7ca93-ce4c-4f42-a0a4-b3f0e34c4fa5)
### SKALE Chains
![Image](https://github.com/user-attachments/assets/f80f4eef-91bd-4bf5-bbbc-e42d461b90ff)
### Staking
![Image](https://github.com/user-attachments/assets/7e6a1994-8b0e-4cb5-8e35-d76bd2268848)
### On-Ramp
Is not available on QA network.
