### ISSUE TITLE
Add email field to profile

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/portal#366]
Users who connected their wallet and signed in should be able to add their email to complete a profile. 

After signing in a new banner will be displayed on the Home and Ecosystem pages:
<img width="888" alt="Screenshot 2024-10-25 at 15 34 25" src="https://github.com/user-attachments/assets/42d2a85e-4db2-4580-8fba-7c4ecb633829">

User should be able to set their email and then go to SKALE Swell to finish the quest.

**Comment by yatsunastya** [comment]
Checked ✅
Version: [3.1.0-beta.0](https://github.com/skalenetwork/portal/releases/tag/3.1.0-beta.0)

After connecting wallet, Swell banner is displayed on Home and Ecosystem pages. 
![Image](https://github.com/user-attachments/assets/2feab6bb-f1f3-4b44-8926-d9fa34ceeb56)

After signing-in, it's possible to add an e-mail. And after adding the e-mail, button "Claim Rewards" is displayed on profile page. 
![Image](https://github.com/user-attachments/assets/30e92d7b-0f69-4553-a645-c1080c51ac17)

**Comment by PolinaKiporenko** [comment]
Will be rescope from current release
