### ISSUE TITLE
Add trending app rankings based on the number of transactions during last N days

### ISSUE THREAD

**Issue by PolinaKiporenko** [skalenetwork/portal#371]
In the next version of Portal we need to calculate and display app rankings based on the number of likes that authorised users leave on the Portal.

**Comment by yatsunastya** [comment]
Checked ✅
Version: [3.1.0-beta.0](https://github.com/skalenetwork/portal/releases/tag/3.1.0-beta.0)

There are 12 apps on the Trending page.
They are ranked according to the number of transaction of these apps.
 ![Image](https://github.com/user-attachments/assets/e6067cea-148d-4c10-ab98-a4678ce04d2a)
