### ISSUE TITLE
Update Pre-TGE tags logic

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/portal#374]
Currently pre-tge is a simple category tag, without an ability for dApp devs to provide timestamps when pre-tge tag should be displayed. 

This has to be updated, devs should be able to specify start and end dates for pre-tge tags (should be optional)

Both portal and app submission template in skale-network should be updated.

**Comment by dmytrotkk** [comment]
Testing:

- Add pre-tge tag only to categories `"pretge": null` - should be always displayed
- Add pre-tge to app metadata

```json
{
...
    "pretge": {
        "from": 13534612346, // timestamp
         "to": 3572457245724, // timestamp
    }
}
```


if the current date is in range, pretge chip should be displayed 

@yatsunastya

**Comment by yatsunastya** [comment]
Checked ✅
Version: [3.1.0-beta.1](https://github.com/skalenetwork/portal/releases/tag/3.1.0-beta.1)

If add pre-tge tag only to categories (in chains.json), pre-tge tag and category are always displayed on the app page.
If add pre-tge tag to categories and set time limits, pre-tge tag is displayed only during set time BUT pre-tge category doesn't disappear. 
[Relevant ticket](https://github.com/skalenetwork/portal/issues/408)
