### ISSUE TITLE
Add Recommended dApps section

### ISSUE THREAD

**Issue by PolinaKiporenko** [skalenetwork/portal#377]
Recommended dApps section will be added based on the user's favorite list. For example, if a user has only PC games favorited, then the Recommended section will include PC games that the user did not favorite.

**Comment by yatsunastya** [comment]
Checked ✅
Version: [3.1.0-beta.1](https://github.com/skalenetwork/portal/releases/tag/3.1.0-beta.1)

Recommended apps are displayed on the Home page below "Your Favorites" and it shows apps with the same category names.
![Image](https://github.com/user-attachments/assets/94c9993e-ff67-497a-ba21-1459fd2dc2ea)

Recommended apps are also displayed on the each app page ("Discover more" section)
![Image](https://github.com/user-attachments/assets/110115ce-1590-4d2a-a1c9-fa8b7513adeb)
