### ISSUE TITLE
Scope Ecosystem Signature Request to just Ecosystem Page

### ISSUE THREAD

**Issue by TheGreatAxios** [skalenetwork/portal#379]
- Popup to sign request should only occur on ecosystem page
- QOL improvement

**Comment by dmytrotkk** [comment]
Updated logic in Portal 3.1:

- Sign-in is not requested after wallet connection on any page
- Sign-in message popup is triggered only if the user explicitly clicks on the "Sign in" button or tries to add an app to favorites.

**Comment by yatsunastya** [comment]
Checked ✅
Version: [3.1.0-beta.0](https://github.com/skalenetwork/portal/releases/tag/3.1.0-beta.0)

:heavy_check_mark: "Sign in" is not requested on any page
:heavy_check_mark: "Sign in" is requested by clicking on "Sign in" button
:heavy_check_mark: "Sign in" is requested by adding to fav an app
