### ISSUE TITLE
Add functionality to claim rewards from Paymaster

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/portal#394]
New functionality should be added to the "Manage Validator" page.

Validators should be able to see the amount of available rewards on Paymaster and be able to claim rewards on the chain.

`skale-contracts` library should be used for calls and transactions.

The separate block should be added after the main validator info.

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: [3.2.0-beta.0](https://github.com/skalenetwork/portal/releases/tag/3.2.0-beta.0)

Before claiming chain rewards
![Image](https://github.com/user-attachments/assets/fac2cceb-fdeb-44a6-baea-4c55fe3b7dbf)

After claiming chain rewards
![Image](https://github.com/user-attachments/assets/dfb85076-ad5d-4734-a6b0-dbc9ed95397f)
