### ISSUE TITLE
M2S (goerli) transfers don't work with enkrypt wallet 

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/portal#60]
**Describe the bug**
While trying to send ETH from Mainnet (Goerli) to schain, transaction is endlessly sending. 

**To Reproduce**
1. Create transfer from Mainnet to exchange chain
2. Confirm it in metaport and enkrypt popup window 
3. Check your account activity in ankrypt wallet 

**Expected behavior**
Transaction successfully completed. "You've successfully transferred..." message is displayed. Balances of source and destination chains are changed

**Screenshots**
<img width="1412" alt="Знімок екрана 2023-03-21 о 18 55 10" src="https://user-images.githubusercontent.com/105824131/226712700-06b834ee-22bf-4adf-9ffd-da8a2f400aae.png">

<img width="1432" alt="Знімок екрана 2023-03-21 о 18 47 33" src="https://user-images.githubusercontent.com/105824131/226712350-09c7230b-a42a-4ab7-971b-6b8e03880fc7.png">

<img width="431" alt="Знімок екрана 2023-03-21 о 19 18 58" src="https://user-images.githubusercontent.com/105824131/226718209-dfd1e750-3360-4961-bad5-5f1754130b9b.png">

**Desktop (please complete the following information):**
 - OS: macOS 13.0.1
 - Browser: Chrome
 - Version: 111.0.5563.64
 - Enkrypt version: [v1.13.0](https://github.com/enkryptcom/enKrypt/releases/tag/v1.13.0)

**Comment by dmytrotkk** [comment]
should be fixed by now, needs to be retested

**Comment by dmytrotkk** [comment]
has to be re-tested, changing status to `QA`

**Comment by yatsunastya** [comment]
There are still issues with transfers via Enkrypt. 
1. Transaction - isn't shown in Enkrypt wallet but balance is changed,
                         - is shown as stuck in Metaport, 
                         - is shown as successful on [Etherscan](https://goerli.etherscan.io/tx/0x523dfdc26d185f5678209afeb953578e45c500d45d23fd16fc42ea4fae1de2de)
2. Transaction is failed ⬇️


![Image](https://github.com/skalenetwork/bridge-ui/assets/105824131/449cb70e-7eb2-4cf1-83f2-1897b5232f84)

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: [3.1.0-beta.3](https://github.com/skalenetwork/portal/releases/tag/3.1.0-beta.3)

Issue isn't relevant anymore.
